#!/usr/bin/env bash
# ShelfOS — set up the label printer attached to THIS machine.
#
# This file is generated by ShelfOS with your answers already filled in. It sets
# up two user services on this computer: a bridge that puts the printer on a
# local port, and an SSH tunnel that carries that port to the server. Nothing
# here changes ShelfOS itself.
#
# It asks for sudo three times at most, and never more than these:
#   * a udev rule, so the printer keeps one name across replugs;
#   * adding you to a group, so you may open the printer without root;
#   * enabling linger, so the services run when you are not logged in.
# Everything else lands in your home directory. Read the file before running it.
#
#   less shelfos-label-setup.sh
#   bash shelfos-label-setup.sh --dry-run
#   bash shelfos-label-setup.sh
#
# Options: --dry-run, --uninstall, --show-bridge, --skip-ssh-check, --help.

# -E so the ERR trap survives functions and subshells; without it the trap is
# silently not inherited and a failure inside a function reports nothing.
set -Eeuo pipefail

SSH_USER="@SSH_USER@"
SSH_HOST="@SSH_HOST@"
SSH_PORT="@SSH_PORT@"
DEVICE="@DEVICE@"
BRIDGE_PORT="@BRIDGE_PORT@"
GROUP="@GROUP@"
BRIDGE_SHA256="@BRIDGE_SHA256@"
# Where this machine registers its own key, and the token that lets it. Both are
# put here by ShelfOS when the script is downloaded. Empty when this server was
# not set up for it, or when the account that downloaded it may not register a
# machine — the script then prints what to run on the server instead.
SHELFOS_URL="@SHELFOS_URL@"
ENROLL_TOKEN="@ENROLL_TOKEN@"

BRIDGE_PATH="$HOME/.local/lib/shelfos/label_bridge.py"
# This machine's own key for the tunnel, made here and kept here. The private
# half never travels: ShelfOS hands out this script, not a credential, so
# opening the page can never be a way to obtain ssh access to the server.
KEY_PATH="$HOME/.ssh/shelfos-label"
UNIT_DIR="$HOME/.config/systemd/user"
BRIDGE_UNIT="$UNIT_DIR/shelfos-label.service"
TUNNEL_UNIT="$UNIT_DIR/shelfos-label-tunnel.service"
UDEV_RULE="/etc/udev/rules.d/99-shelfos-label.rules"
UDEV_LINE='SUBSYSTEM=="usbmisc", ATTRS{idVendor}=="04f9", MODE="0660", GROUP="'"$GROUP"'", SYMLINK+="shelfos-label"'

DRY_RUN=0
UNINSTALL=0
SKIP_SSH_CHECK=0

RED=""; GREEN=""; YELLOW=""; BOLD=""; OFF=""
if [ -t 1 ]; then
    RED=$'\033[31m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'
    BOLD=$'\033[1m'; OFF=$'\033[0m'
fi

step()    { printf '%s==>%s %s\n' "$BOLD" "$OFF" "$*"; }
step_ok() { printf '    %sok%s %s\n' "$GREEN" "$OFF" "$*"; }
skipped() { printf '    -- %s\n' "$*"; }
warn()    { printf '    %swarning%s %s\n' "$YELLOW" "$OFF" "$*" >&2; }
die()     { printf '%serror%s %s\n' "$RED" "$OFF" "$*" >&2; exit 1; }

trap 'die "failed at line $LINENO"' ERR

usage() {
    sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'
    exit 0
}

while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run) DRY_RUN=1 ;;
        --uninstall) UNINSTALL=1 ;;
        --skip-ssh-check) SKIP_SSH_CHECK=1 ;;
        --show-bridge) decode_bridge_and_exit=1 ;;
        -h|--help) usage ;;
        *) die "unknown option: $1 (try --help)" ;;
    esac
    shift
done

# The bridge itself, byte for byte the file from the ShelfOS repository, in
# base64 so nothing in it can break out of the quoting here. Its sha256 is in
# BRIDGE_SHA256 above and is checked after decoding; `--show-bridge` prints it
# so you can read the code you are about to install.
decode_bridge() {
    base64 -d <<'SHELFOS_BRIDGE_BASE64'
@BRIDGE_BASE64@
SHELFOS_BRIDGE_BASE64
}

if [ "${decode_bridge_and_exit:-0}" = 1 ]; then
    decode_bridge
    exit 0
fi

# Every command that changes something goes through this, so --dry-run is a
# property of one function rather than a promise repeated at each call site.
run() {
    if [ "$DRY_RUN" = 1 ]; then
        printf '    would run: %s\n' "$*"
        return 0
    fi
    "$@"
}

# Write a file only when its content differs, so a second run says "unchanged"
# rather than restarting services for nothing.
write_file() {
    local path="$1" content="$2"
    if [ -f "$path" ] && [ "$(cat "$path")" = "$content" ]; then
        skipped "$path is already what it should be"
        return 1
    fi
    if [ "$DRY_RUN" = 1 ]; then
        printf '    would write: %s\n' "$path"
        return 0
    fi
    mkdir -p "$(dirname "$path")"
    printf '%s\n' "$content" > "$path"
    step_ok "wrote $path"
    return 0
}

need() {
    command -v "$1" >/dev/null 2>&1 || die "$1 is needed and is not installed$2"
}

# ---------------------------------------------------------------- preflight

# The single most important line in this file. Under sudo, everything below
# would be set up for root: root's user units, root's linger, root's home — two
# services nobody would think to look for, while yours never start.
if [ "$(id -u)" = 0 ]; then
    die "do not run this as root or with sudo — it asks for sudo where it needs it"
fi

step "Checking what this machine has"
need python3 ""
need ssh " (install openssh-client)"
need base64 ""
need systemctl " — this script sets up systemd user services"
need ssh-keygen " (install openssh-client)"
need timeout " (it is in coreutils)"
PYTHON="$(command -v python3)"
SSH_BIN="$(command -v ssh)"

# A user manager is not a given: over plain ssh without linger there is no user
# bus at all, and then every `systemctl --user` fails with a message nobody
# connects to the cause.
if [ -z "${XDG_RUNTIME_DIR:-}" ] || ! systemctl --user is-system-running >/dev/null 2>&1; then
    die "no systemd user session here (XDG_RUNTIME_DIR is unset or the user manager is not running).
    Log in at the desktop, or as this user run: loginctl enable-linger $USER, then log in again."
fi
step_ok "python3, ssh, base64 and a running systemd user manager"

# --------------------------------------------------------------- uninstall

if [ "$UNINSTALL" = 1 ]; then
    step "Removing the services"
    run systemctl --user disable --now shelfos-label-tunnel.service || true
    run systemctl --user disable --now shelfos-label.service || true
    run rm -f "$BRIDGE_UNIT" "$TUNNEL_UNIT" "$BRIDGE_PATH"
    run systemctl --user daemon-reload
    step "Removing the udev rule (sudo)"
    run sudo rm -f "$UDEV_RULE"
    run sudo udevadm control --reload
    step_ok "removed"
    printf '\n%s\n' "Left alone on purpose: $KEY_PATH, your membership of the '$GROUP'
group, and linger for $USER. The last two may be older than this script and may be
holding up something else; the key is yours and removing it here would not
withdraw anything anyway. To undo them yourself:
    on the server:  ./shelfos.sh tunnel-key remove $(hostname -s 2>/dev/null || printf '<this machine>')
    here:           rm -f $KEY_PATH $KEY_PATH.pub
                    sudo gpasswd -d $USER $GROUP
                    loginctl disable-linger $USER"
    exit 0
fi

# ------------------------------------------------------------------- ssh

step "The key this machine logs in with"
if [ -f "$KEY_PATH" ]; then
    step_ok "$KEY_PATH is already here"
elif [ "$DRY_RUN" = 1 ]; then
    printf '    would run: ssh-keygen -t ed25519 -f %s\n' "$KEY_PATH"
else
    mkdir -p "$HOME/.ssh"
    chmod 0700 "$HOME/.ssh"
    ssh-keygen -q -t ed25519 -N "" -C "shelfos-label@$(hostname -s)" -f "$KEY_PATH"
    step_ok "made $KEY_PATH — its private half stays on this machine"
fi
PUBLIC_KEY=""
[ -f "$KEY_PATH.pub" ] && PUBLIC_KEY="$(cat "$KEY_PATH.pub")"

# What the server must be told, for the times this script cannot tell it itself.
# One line, ready to paste; the account it authorises can do nothing but bind
# the one port.
authorize_hint() {
    printf '%s\n' "On the server, in the ShelfOS checkout, run:

        ./shelfos.sh tunnel-key add \"$PUBLIC_KEY\"

    then run this script again."
}

# Hand the public half to ShelfOS, which is where the person running this is
# already signed in. That is the whole point of the exercise: no account on the
# server, no logging in to it, nothing to do there at all.
#
# Only the PUBLIC half ever moves. The token came with this download, may do
# this one thing, and expires.
register_with_shelfos() {
    [ -n "$SHELFOS_URL" ] && [ -n "$ENROLL_TOKEN" ] || return 2
    "$PYTHON" - "$SHELFOS_URL" "$ENROLL_TOKEN" "$PUBLIC_KEY" <<'SHELFOS_ENROLL_EOF'
import json
import sys
import urllib.error
import urllib.request

url, token, public_key = sys.argv[1], sys.argv[2], sys.argv[3]
request = urllib.request.Request(
    url.rstrip("/") + "/api/labels/setup/enroll",
    data=json.dumps({"public_key": public_key}).encode(),
    headers={
        "Content-Type": "application/json",
        "Authorization": "Bearer " + token,
    },
    method="POST",
)
try:
    with urllib.request.urlopen(request, timeout=20) as response:
        answer = json.load(response)
    print(f"registered as {answer['comment']} ({answer['fingerprint']})")
except urllib.error.HTTPError as error:
    try:
        detail = json.load(error).get("detail", "")
    except Exception:
        detail = error.reason
    print(f"{error.code} {detail}", file=sys.stderr)
    sys.exit(1)
except OSError as error:
    print(f"cannot reach {url}: {error}", file=sys.stderr)
    sys.exit(1)
SHELFOS_ENROLL_EOF
}

step "Registering this machine with ShelfOS"
if [ "$DRY_RUN" = 1 ]; then
    printf '    would send this machine\047s public key to %s\n' "${SHELFOS_URL:-(not offered)}"
else
    enroll_status=0
    register_with_shelfos || enroll_status=$?
    if [ "$enroll_status" = 0 ]; then
        step_ok "ShelfOS accepted the key — nothing to do on the server"
    elif [ "$enroll_status" = 2 ]; then
        # No token came with the download: either this server was not set up to
        # register printers, or the account that downloaded the script may not
        # (a read-only account may read the page, but not change what the server
        # accepts). The key still has to be authorised, so say how.
        warn "this copy of the script cannot register itself, so the key has to be
    authorised on the server once.

    $(authorize_hint)"
    else
        warn "ShelfOS did not accept the key; the message above says why. If the
    registration token has expired, download the script again. Otherwise:

    $(authorize_hint)"
    fi
fi

if [ "$SKIP_SSH_CHECK" = 1 ]; then
    warn "skipping the ssh check: if the key is not authorized or the port is taken,
    the tunnel will sit in 'activating' and retry for ever, saying nothing useful."
elif [ "$DRY_RUN" = 1 ]; then
    printf '    would check: the host key, then the reverse forward to %s\n' "$SSH_HOST"
else
    step "Checking ssh to $SSH_USER@$SSH_HOST"
    # A tunnel already running would hold the very port this is about to ask
    # for, and the test would report the trouble it is itself causing.
    if systemctl --user is-active --quiet shelfos-label-tunnel.service 2>/dev/null; then
        systemctl --user stop shelfos-label-tunnel.service
    fi

    # The real thing, not a proxy for it: exactly the connection the unit makes.
    #
    # `true` over ssh would have tested a session, which an authorized_keys entry
    # restricted to forwarding refuses on purpose — the check would have failed
    # on a setup that works perfectly. Asking ssh-keygen whether the host key is
    # known would have been guesswork too: ssh finds ~ through the password file,
    # not $HOME, so the file it reads is not always the file that would be
    # searched. So there is one attempt, and what it says is what is reported.
    # It succeeds only when the host key is known, the key is authorized AND the
    # port is free on the server — between them every way the tunnel fails.
    ssh_error="$(mktemp "${TMPDIR:-/tmp}/shelfos-ssh.XXXXXX")"
    # Inside `if`, not after `set +e`: an ERR trap fires on a failing command
    # whether errexit is on or not, so the failure this test EXPECTS would be
    # reported as "failed at line …" before anything could read it. A condition
    # is the one place bash agrees not to.
    if timeout 8 ssh -N -T \
        -o BatchMode=yes -o NumberOfPasswordPrompts=0 -o ConnectTimeout=10 \
        -o ExitOnForwardFailure=yes -o IdentitiesOnly=yes -i "$KEY_PATH" \
        -p "$SSH_PORT" -R "127.0.0.1:$BRIDGE_PORT:127.0.0.1:$BRIDGE_PORT" \
        "$SSH_USER@$SSH_HOST" 2>"$ssh_error"
    then
        ssh_status=0
    else
        ssh_status=$?
    fi
    # 124 is `timeout` ending a connection that was still up — which is success:
    # the forward was granted and held. Anything else is ssh giving up.
    if [ "$ssh_status" = 124 ]; then
        step_ok "the tunnel comes up, and $SSH_HOST let it bind $BRIDGE_PORT"
        rm -f "$ssh_error"
    else
        ssh_says="$(cat "$ssh_error")"
        rm -f "$ssh_error"
        case $ssh_says in
            *"Host key verification failed"*|*"Host key for"*"changed"*)
                # Never accepted for anyone: that check is the only thing making
                # the connection mean anything, and a script cannot look at a
                # fingerprint and recognise it.
                die "the host key of $SSH_HOST has not been accepted on this machine.
    Connect once by hand, look at the fingerprint, and accept it:
        ssh -p $SSH_PORT $SSH_USER@$SSH_HOST
    then run this script again." ;;
            *"Permission denied"*|*"Too many authentication failures"*)
                die "$SSH_HOST would not let $SSH_USER in with this machine's key.

    Usually that means the key is not authorized there yet:

    $(authorize_hint)

    If ShelfOS said it accepted the key, then that server admits only named
    accounts (AllowUsers/AllowGroups in its sshd configuration) and $SSH_USER is
    not one of them — which is for whoever runs it to change." ;;
            *"remote port forwarding failed"*)
                # ssh says the same sentence for a port in use and a port its
                # configuration will not hand over, so name both rather than
                # send someone looking for a process that is not there.
                die "$SSH_HOST would not let this bind port $BRIDGE_PORT. Either something
    there is already using it, or that server does not allow this port. If you
    changed the port on the ShelfOS page, download the script again so that all
    three ends agree; otherwise ask whoever runs the server to look at
    'journalctl -u ssh' there, which says which of the two it is." ;;
            *)
                die "ssh to $SSH_USER@$SSH_HOST did not work:

    ${ssh_says:-(it said nothing at all)}" ;;
        esac
    fi
fi

# ------------------------------------------------------------------ udev

step "Naming the printer /dev/shelfos-label (sudo)"
if [ -e "$UDEV_RULE" ] && [ "$(sudo cat "$UDEV_RULE" 2>/dev/null || true)" = "$UDEV_LINE" ]; then
    skipped "$UDEV_RULE is already what it should be"
else
    other_rule="$(grep -rl 'shelfos-label' /etc/udev/rules.d 2>/dev/null | grep -v "^$UDEV_RULE$" || true)"
    if [ -n "$other_rule" ]; then
        warn "another rule already creates shelfos-label:
    $other_rule
    Leaving both alone — two rules for one name is how you get the wrong device."
    else
        if [ "$DRY_RUN" = 1 ]; then
            printf '    would write (sudo): %s\n' "$UDEV_RULE"
        else
            printf '%s\n' "$UDEV_LINE" | sudo tee "$UDEV_RULE" >/dev/null
            step_ok "wrote $UDEV_RULE"
        fi
        run sudo udevadm control --reload
        run sudo udevadm trigger --subsystem-match=usbmisc
    fi
fi

# ----------------------------------------------------------------- group

step "Letting you open the printer without root"
if id -nG | tr ' ' '\n' | grep -qx "$GROUP"; then
    skipped "you are already in the '$GROUP' group"
else
    # -aG, never -G: the second form REPLACES every group you are in, sudo
    # included, and people have locked themselves out of their own machine that
    # way. This is worth the sentence.
    run sudo usermod -aG "$GROUP" "$USER"
    warn "you were added to '$GROUP', which takes effect at your NEXT login.
    Printing works after you log out and back in; the rest of this carries on now."
fi

# ------------------------------------------------------------ the printer

step "Looking for the printer"
if [ -e "$DEVICE" ]; then
    step_ok "$DEVICE is there"
else
    warn "$DEVICE does not exist yet. Usual reasons: the printer is off or
    unplugged; a QL-800 fresh from the box is in Editor Lite mode and shows up as
    a USB drive instead of a printer (hold its Editor Lite button for a second
    until the light goes out); or the rule above needs a replug. The bridge
    starts anyway and will find the printer when it appears."
fi

if command -v lpstat >/dev/null 2>&1 && lpstat -v 2>/dev/null | grep -qi 'usb.*brother'; then
    warn "CUPS has a queue for a Brother printer on USB. CUPS's usb backend takes
    the device away from the kernel driver mid-job, which looks like the printer
    dying halfway through a label. Remove the queue if you print through ShelfOS:
        lpstat -v          # find its name
        sudo lpadmin -x QL-800
    Not done automatically: that is somebody's configured printer, not mine."
fi

# ----------------------------------------------------------------- bridge

step "Installing the bridge"
# Hashed straight out of the decoder, not out of a variable: command
# substitution eats trailing newlines, so a checksum taken from "$bridge_source"
# would never match the file it came from.
got_sha="$(decode_bridge | sha256sum | cut -d' ' -f1)"
bridge_source="$(decode_bridge)"
if [ "$got_sha" != "$BRIDGE_SHA256" ]; then
    die "the embedded bridge does not match its checksum — this file arrived damaged.
    Expected $BRIDGE_SHA256
    Got      $got_sha
    Download it from ShelfOS again."
fi
step_ok "checksum matches ($BRIDGE_SHA256)"
if write_file "$BRIDGE_PATH" "$bridge_source"; then
    run chmod 0755 "$BRIDGE_PATH"
fi
if [ "$DRY_RUN" != 1 ]; then
    # Checked again where it landed, not only where it came from: the write goes
    # through a shell variable, and the file on disk is what will actually run.
    installed_sha="$(sha256sum "$BRIDGE_PATH" | cut -d' ' -f1)"
    [ "$installed_sha" = "$BRIDGE_SHA256" ] || die "$BRIDGE_PATH does not match its
    checksum after being written. Nothing else has been changed."
fi

# ------------------------------------------------------------------ units

# printf with the values as ARGUMENTS, not a heredoc built by substitution:
# systemd's ExecStart is not a shell, so a value with a space in it would be
# split into arguments no quoting here could put back together. The values were
# validated by ShelfOS before this file was written; this is the second wall.
bridge_unit="$(printf '%s\n' \
    "[Unit]" \
    "Description=Expose the label printer on 127.0.0.1:$BRIDGE_PORT" \
    "" \
    "[Service]" \
    "ExecStart=$PYTHON $BRIDGE_PATH --device $DEVICE --port $BRIDGE_PORT" \
    "Restart=always" \
    "RestartSec=5" \
    "" \
    "[Install]" \
    "WantedBy=default.target")"

tunnel_unit="$(printf '%s\n' \
    "[Unit]" \
    "Description=Reverse tunnel carrying the label printer to $SSH_HOST" \
    "After=shelfos-label.service" \
    "" \
    "[Service]" \
    "ExecStart=$SSH_BIN -N -T -o ExitOnForwardFailure=yes -o ServerAliveInterval=30 -o ServerAliveCountMax=3 -o IdentitiesOnly=yes -o BatchMode=yes -i $KEY_PATH -p $SSH_PORT -R 127.0.0.1:$BRIDGE_PORT:127.0.0.1:$BRIDGE_PORT $SSH_USER@$SSH_HOST" \
    "Restart=always" \
    "RestartSec=5" \
    "" \
    "[Install]" \
    "WantedBy=default.target")"

step "Writing the two services"
changed=0
write_file "$BRIDGE_UNIT" "$bridge_unit" && changed=1
write_file "$TUNNEL_UNIT" "$tunnel_unit" && changed=1
[ "$changed" = 0 ] || run systemctl --user daemon-reload

step "Making them run without you logged in (sudo)"
if loginctl show-user "$USER" -p Linger 2>/dev/null | grep -q 'Linger=yes'; then
    skipped "linger is already on for $USER"
else
    run sudo loginctl enable-linger "$USER"
fi

step "Starting them"
run systemctl --user enable --now shelfos-label.service shelfos-label-tunnel.service
if [ "$changed" = 1 ]; then
    run systemctl --user restart shelfos-label.service shelfos-label-tunnel.service
fi

if [ "$DRY_RUN" = 1 ]; then
    printf '\n%s\n' "Dry run: nothing was changed, and sudo was never called."
    exit 0
fi

# ------------------------------------------------------------------ check

step "Checking that it works"
for unit in shelfos-label.service shelfos-label-tunnel.service; do
    for _ in 1 2 3 4 5 6 7 8 9 10; do
        systemctl --user is-active --quiet "$unit" && break
        sleep 1
    done
    if systemctl --user is-active --quiet "$unit"; then
        step_ok "$unit is running"
    else
        printf '\n' >&2
        journalctl --user -u "$unit" -n 15 --no-pager >&2 || true
        die "$unit did not start; its last lines are above."
    fi
done

# The same three bytes and the same 32-byte answer the application uses, asked
# here on this machine. A green pair of units only says the processes are up;
# this says the printer is actually on the other end of them.
if "$PYTHON" - "$BRIDGE_PORT" <<'SHELFOS_PROBE_EOF'
import socket, sys, time

port = int(sys.argv[1])
try:
    with socket.create_connection(("127.0.0.1", port), timeout=5) as s:
        s.sendall(b"\x1b\x69\x53")
        s.settimeout(0.5)
        deadline = time.monotonic() + 5
        data = b""
        while time.monotonic() < deadline and len(data) < 32:
            try:
                chunk = s.recv(32 - len(data))
            except socket.timeout:
                continue
            if not chunk:
                break
            data += chunk
        sys.exit(0 if len(data) >= 32 else 1)
except OSError:
    sys.exit(1)
SHELFOS_PROBE_EOF
then
    step_ok "the printer answered on 127.0.0.1:$BRIDGE_PORT"
else
    warn "the bridge is listening, but the printer did not answer. It is usually
    not plugged in, still in Editor Lite mode, or held by CUPS. Look at:
        journalctl --user -u shelfos-label -n 20"
fi

printf '\n%s\n' "Done. On this machine there are now:
    $KEY_PATH
    $BRIDGE_PATH
    $BRIDGE_UNIT
    $TUNNEL_UNIT
    $UDEV_RULE
Watch them with:  systemctl --user status shelfos-label shelfos-label-tunnel
Undo them with:   bash $0 --uninstall
Then go back to ShelfOS and press Test connection."
