"""Stock movement ledger (spec §17).

This ledger is the source of truth for quantities (decision D1). Each row is an
immutable record of a delta applied to a (component, location) pair.
"""

from __future__ import annotations

from datetime import UTC, datetime

from sqlmodel import Field, SQLModel

from app.models.enums import StockReason, enum_column


class StockMovement(SQLModel, table=True):
    __tablename__ = "stock_movements"

    id: int | None = Field(default=None, primary_key=True)
    component_id: int = Field(foreign_key="components.id")
    location_id: int = Field(foreign_key="locations.id")
    delta_quantity: int
    reason: StockReason = Field(sa_column=enum_column(StockReason))
    note: str | None = Field(default=None)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))
    user_id: int = Field(foreign_key="users.id")
    # Set when the movement is generated by finalizing an invoice (spec §16).
    invoice_id: int | None = Field(default=None, foreign_key="invoices.id")
